### PR TITLE
Added multiline support and some cleanup done

### PR DESCRIPTION
**Pull request by thbe**
I've added multiline support to "typewritten" with user and host as I need this for the distinction of target nodes when I use multiple terminals. It can be activated by setting the TYPEWRITTEN_MULTILINE=true in .zshrc.

### CODE REVIEW

**Comment by reobin** [comment]
Hey! thanks a lot, that's awesome. I'd like to use that personally.

I changed some stuff around as this was for me an early version.\
Would you mind pulling master, merge, and commit again?

**Comment by thbe** [comment]
I've merged your changes into my fork and refactored the multiline part. The additional commits should be included in this PR, at least I hope so ... :)

**Comment by reobin** [comment]
Thank you @thbe ! Changed up the colors a little bit, hope you don't mind

**Comment by thbe** [comment]
No, the new color-coding looks awesome!

**Comment by thbe** [comment]
BTW., I've changed the link in my corresponding blog post (https://www.thbe.org/posts/2020/01/02/Lean_zsh_terminal.html) to your repository instead of mine. I also updated my repository which will only be used for PRs as needed. Thanks for the fast PR inclusion!

**Comment by reobin** [comment]
@all-contributors please add @thbe for code

**Pull request merged**
