### PR TITLE
feat: Implement pure and half_pure layouts

### LINKED ISSUE #31: Align right prompt
**Is your feature request related to a problem? Please describe.**

When adding/removing files in a git dir, the right prompt varies:

Screenshot 2020-06-17 at 09 49 11

It ends up looking unorganised and a bit chaotic in my opinion.

**Describe the solution you'd like**

Align the `->` characters in all the right prompts if that's possible 🤔

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by reobin**
Closes #31 

Will not merge this yet as I am not satisfied with the code, but the branch can be checked out to use the new layouts already.

### CODE REVIEW

**Comment by jletey** [comment]
@reobin Strange, when I try to use this branch:

```sh
# ~/.dotfiles/zsh/plugins.txt

zsh-users/zsh-autosuggestions branch:develop
zsh-users/zsh-syntax-highlighting
reobin/typewritten branch:feat/implement-new-layouts
```

And run `antibody update`, it doesn't work 🤔

**Comment by reobin** [comment]
I had issues with that too, run `antibody purge reobin/typewritten` then add it again with the right branch @jletey

**Comment by jletey** [comment]
@reobin Thx for that, works now! Wowee I'm rlly loving the `half_pure` option 😍

**Comment by reobin** [comment]
Yep I really like it too!

gonna have to go ahead and give credit to pure in the readme for inspiration now ahah

Taking the weekend off for now, but I should merge this next monday!

**Comment by jletey** [comment]
Haha yeah I guess you have to now 😂 Have a good weekend bud!

**Comment by jletey** [comment]
@reobin Just something I've noticed when using `half_pure`. When you are in a git dir, there is a newline before the prompt. But if you aren't, there isn't. I'd prefer to have a newline always 😁

Screenshot 2020-06-27 at 12 52 57

**Comment by reobin** [comment]
@jletey Oh yeah I wasn’t sure about this one, thanks for the feedback! I’ll push something if I have some time today

**Comment by reobin** [comment]
@jletey Fixed it for half_pure :)

So I'm waiting a bit more on merging this because it breaks the virtual env display for python.

I'll fix that and will be able to merge

**Pull request merged**
