### PR TITLE
docs: Add package manager instructions

### PR DESCRIPTION
**Pull request by jletey**
To verify locally:

```diff
- antibody bundle reobin/typewritten
+ antibody bundle reobin/typewritten branch:feat/zsh-bundle
```

```diff
- zplug reobin/typewritten, as:theme
+ zplug reobin/typewritten, at:feat/zsh-bundle, as:theme
```

### CODE REVIEW

**Comment by reobin** [comment]
Thanks so much man! I'll try to add some today, and merge it later 🎉

**Comment by jletey** [comment]
@reobin No problem, might add some more too :)

**Comment by reobin** [comment]
I'm trying antigen, and I can't find any docs on how to specify a branch for the theme, so I guess it will have to be added after having updated master. On to more...

**Comment by reobin** [comment]
Zgen works with the line 
```bash
zgen load reobin/typewritten typewritten
```

To test it right now:
```bash
zgen load reobin/typewritten typewritten feat/zsh-bundle
```

**Comment by reobin** [comment]
zim also works by adding:
```bash
zmodule reobin/typewritten --name typewritten
```
To test it right now add the branch option:
```bash
--branch feat/zsh-bundle
```

**Comment by jletey** [comment]
@reobin Sweet! Do you want to add those, or can I do it?

**Comment by reobin** [comment]
You can go ahead and add it to your merge request. Makes sense this way

**Comment by reobin** [comment]
So last ones would be antigen (to test later) and prezto which seems like heavy stuff, but I'll try

**Comment by reobin** [comment]
Ok so it seems that prezto bundles some packages with its installation.

Some of them on the official repo, some of them on the [prezto-contrib](https://github.com/belak/prezto-contrib) repo.

A merge request could be done later to add typewritten to prezto as an external theme.
We can worry about this later.

**Comment by reobin** [comment]
@all-contributors please add @johnletey for doc

**Comment by johnletey** [comment]
Thanks @reobin 😁

**Comment by diffficult** [comment]
> Ok so it seems that prezto bundles some packages with its installation.
> 

so far seems to be working if you clone the repo as `contrib-prompt/external/typewritten` and linking `typewritten.zsh` as `prompt_typewritten_zsh` in `contrib-prompt/functions`. There are some minor glitches when trying to preview other prompts and I need to further test if all the prompt layour options work fine.

**Pull request merged**
