### PR TITLE
Add Home`brew install` instructions

### PR DESCRIPTION
**Pull request by danielbayley**
Depends on https://github.com/Homebrew/homebrew-core/pull/102813.

### CODE REVIEW

**Comment by danielbayley** [comment]
@reobin This has been merged upstream…

**Comment by reobin** [comment]
Thanks @danielbayley !  How would one install the theme through brew? What should be added to `.zshrc`? Let's list that in the instructions

**Comment by danielbayley** [comment]
@reobin Done.

**Comment by reobin** [comment]
Awesome @danielbayley, works like a charm

Thank you so much for your work and patience, it's very appreciated 🎉

@all-contributors please add @danielbayley for code, documentation

**Review by reobin — APPROVED** [review]

**Pull request merged**
