### PR TITLE
Added kubecontext to env, after virtual_env

### PR DESCRIPTION
**Pull request by KEDLogic**

### CODE REVIEW

**Comment by reobin** [comment]
Hey @KEDLogic ! Thank you for opening this PR

If you allow me, I'd like to imagine a more generic way to add stuff to either right, or left prompt.

If we were to add a "dynamic" env variable that would be evaluated every time the prompt is displayed, would that allow you to print the kubecontext? I think we could add one of those in some places

**Comment by KEDLogic** [comment]
I had that exact thought actually, but was pressed for time yesterday. 

Yes, a dynamically assigned env variable would work just fine i think.

**Comment by KEDLogic** [comment]
I have something partially done that might do the trick. Will push once complete...

**Comment by KEDLogic** [comment]
There you go. Just the dynamic / customizable part. Extracts out the get_virtual or get_kubecontex into a separate file. Then use `TYPEWRITTENN_EXTRA_ENV=('tw_virtual_env.zsh' 'tw_kubecontex.zsh')`

Thoughts?

**Comment by reobin** [comment]
That's awesome @KEDLogic. I like where this is going.

2 points:

1. If I'm not mistaken, we are changing the current behavior where right now, the python virtual env, or conda prefix, is displayed (when it's defined) by default. This PR changes this behavior since those 2 values will only display if `TYPEWRITTEN_EXTRA_ENV` is defined. No problem, we can easily correct this. I'd like to think about point 2 first.
2. What if we tried to make this solution entirely generic? Instead of using the virtual env spot to display all this new stuff, we can create a new variable (thinking `TYPEWRITTEN_LEFT_PROMPT_PREFIX`? not sure) where a user could decide to display any value they want.
    - In your example, you could display kubecontext
    - In the original issue's example, they could display the timestamp
    - One could display anything by defining `TYPEWRITTEN_LEFT_PROMPT_PREFIX` in `.zshrc`
        - `export TYPEWRITTEN_LEFT_PROMPT_PREFIX=$(date)`
    - Then during the rendering of the prompt, we evaluate the function provided by the user to add a prefix like you did for the env prefix.

What do you think?

**Comment by KEDLogic** [comment]
`export TYPEWRITTEN_LEFT_PROMPT_PREFIX=$(date)` would just display the date when terminal session was started, but I get your point. 
If it was an actual function:
```
export TYPEWRITTEN_LEFT_PROMPT_PREFIX=date
```
then we could eval 
```
tw_left_prompt_prefix="$($TYPEWRITTEN_LEFT_PROMPT_PREFIX)"
```
That would work. Either way the user supplied file/function is being called with the expectation that it returns a string, but this way they don't need to manage additional files if they don't want to.

**Comment by reobin** [comment]
> `export TYPEWRITTEN_LEFT_PROMPT_PREFIX=$(date)` would just display the date when terminal session was started, but I get your point.

That's right, my mistake! Long day!

From what I understand, as a user, you'd like to have some built-in options to work with. That's valid. I think the best option would be to have some built-ins, but also let the user add their own function (or string value). What do you think?

Thanks a bunch for participating in this! I appreciate the help

**Comment by KEDLogic** [comment]
Sounds about right. So probably just the eval approach, but we could add some canned options for defaults. 

I'll try to get something working over the next few days.

**Comment by KEDLogic** [comment]
Haven't had time to touch this yet, but did want to make note of a possible bug with the current commit. I'm noticing a file `1` in every directory that I've visited after this change, contents are:
```bash
~
 ❯ cat 1
error: current-context is not set
error: current-context is not set
```
Brief testing confirms that its generated if `KUBECONFIG` is unset or is set to a file with no current context. 

I've not yet found the code causing the issue, but am busy with work stuff so not really trying at the moment.

**Comment by KEDLogic** [comment]
Fixed the bug with that `1` file. had `2&>1 /dev/null` instead of `2>&1 /dev/null`

Ok, design question time.

I'm currently running with `TYPEWRITTEN_PROMPT_PREFIX` and `TYPEWRITTEN_RIGHT_PROMPT_PREFIX` to minimize changes. Evaling instead of printing string, but there is a use case consideration here:

A user might want to use the prefixes as literal strings instead of custom functions. I see 2 ways of handling this:

1. Have two env vars for each prompt:  `*_PROMPT_PREFIX` and `*_PROMPT_PREFIX_FUNCTION` and either
  a. Have one superceed the other. Eg,  `*_PROMPT_PREFIX` is ignored if `*_PROMPT_PREFIX_FUNCTION`  is set (or vice versa)
  b. Make  `*_PROMPT_PREFIX_FUNCTION` a boolean, maybe called `*_PROMPT_PREFIX_IS_FUNCTION`, and default to either true or false.
2.  Only use `*_PROMPT_PREFIX_FUNCTION` and make a note that to just print a string, use `echo -n $STRING`.

What are your thoughts @reobin ?

**Comment by KEDLogic** [comment]
@reobin  I concur. My recommendation is the 2 env variables, with the 2nd being an "is_function" bool. 

I've got other priorities this week and likely wont touch this. Why don't you take your stab at it?

**Comment by KEDLogic** [comment]
I'm closing this as [PR150](https://github.com/reobin/typewritten/pull/150) will fulfill this.

**Pull request closed without merging**
