### PR TITLE
option to display user@host in singleline prompt

### PR DESCRIPTION
**Pull request by erikr**
Closes issue #7

Your theme is my favorite, and I've spent a lot of time exploring what is available.

Since I regularly set up new machines, your copy-pastable [installation instructions](https://github.com/reobin/typewritten#installation) are helpful and much-appreciated.

Would be great to have this PR merged with master so I don't need to maintain my own fork, and benefit from any subsequent development on this theme!

Thanks for considering.

### CODE REVIEW

**Comment by reobin** [comment]
Nice work @erikr! I really like this, and would like it on master too.

I am thinking that different options that you can enable through `.zshrc` could get confusing to the user as to which would be prioritized over the other. Ex.: If I set both `TYPEWRITTEN_MULTILINE` and `TYPEWRITTEN_SINGLELINE_VERBOSE` to `true`, only one of these layouts will be displayed on your terminal, and it is not clear which.

What do you think of having a `TYPEWRITTEN_PROMPT_LAYOUT` variable instead? It would default to `singleline`, and the `multiline` and `singleline_verbose` could be secondary options. We could then add new layouts later on without breaking anything.

I would keep this `TYPEWRITTEN_MULTILINE` option for a while as some people are using it in this moment, but would deprecate it slowly. I really need to versionize this theme 😅

Anyway, let me know what you think about it.
Thanks again!

**Comment by erikr** [comment]
@reobin Thanks! I like your idea of `TYPEWRITTEN_PROMPT_LAYOUT`. Seems clear! Good point re: people have `TYPEWRITTEN_MULTILINE` enabled.

Perhaps an intermediate version sets the value of `TYPEWRITTEN_PROMPT_LAYOUT` based on 
the value of `TYPEWRITTEN_MULTILINE` so those who set the latter to `true` don't see an undesired change in prompt. Not sure what the best way to deprecate.

**Comment by reobin** [comment]
That would be the best option clearly. But we can about deprecating later. 
For now, let's just define a local variable based on the values of `TYPEWRITTEN_PROMPT_LAYOUT` and `TYPEWRITTEN_MULTILINE` that would be valued to `singleline`, `multiline`, or `singleline_verbose`, and use that local variable for the layout stuff. 

By doing that, the logic of the single layout variable could already be implemented, but we don't break the `TYPEWRITTEN_MULTILINE` use yet.

What do you think?

**Comment by erikr** [comment]
Sounds good! Implemented in https://github.com/reobin/typewritten/pull/8/commits/a8b9506287c7424d69d99b632d9176a7d69c6bcc.

Now there are three options:
1. 
```shell
export TYPEWRITTEN_PROMPT_LAYOUT="singleline"
```

shows:
```
>
```

2. 
```shell
export TYPEWRITTEN_PROMPT_LAYOUT="multiline"
```

shows:
```
user@host
>
```
3.
```shell
export TYPEWRITTEN_PROMPT_LAYOUT="singleline_verbose"
```

shows:
```
user@host >
```

The current if-then logic could be more succinct, but I like being explicit about the default behavior of `PROMPT` if `TYPEWRITTEN_PROMPT_LAYOUT` is not any of the above expected values:
https://github.com/erikr/typewritten/blob/a8b9506287c7424d69d99b632d9176a7d69c6bcc/typewritten.zsh-theme#L49-L59

I also added a deprecation warning if the shell detects a variable `TYPEWRITTEN_MULTILINE`, but that could be annoying:
https://github.com/erikr/typewritten/blob/a8b9506287c7424d69d99b632d9176a7d69c6bcc/typewritten.zsh-theme#L40-L42

**Comment by reobin** [comment]
Really nice work man! I also think the message could get annoying if it shows up every time you open a new terminal instance, although it would be effective.

Remove the message for now, and I'll merge this 👍

I'll update the `readme` with new screenshots and infos about the new option.

Thanks a lot! Good work @erikr

**Comment by erikr** [comment]
Done -- thanks!

**Comment by reobin** [comment]
@all-contributors please add @erikr for code, and doc

**Pull request merged**
